VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsUnidadeAdministrativa"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
  'Regional: 25 - 39ª S R E - UBERABA - PORTE II
  'Unid.Adm.: 5310883  - EE DR LINDOLFO BERNARDES
  'Municipio: 1820 - CONQUISTA                                       UF: MG
  'Distrito: 5  - CONQUISTA
  
Public RegionalCod As Integer
Public RegionalNome As String

Public UnidadeAdmCod As Long
Public UnidadeAdmNome As String

Public MunicipioCod As Long
Public MunicipioNome As String

Public DistritoCod As Long
Public DistritoNome As String

Public ZonaRural As String

Public NaturezaGrupo As Integer
Public NaturezaTipo As Integer
Public NaturezaDescricao As String

Public DataInicio As Date
Public DataFinal As Date
Public DataPublicacao As Date
Public DataProrrogacao As Date




