VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFalta"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get Apuracao() As Date
End Property

Public Property Let Apuracao(ByVal Data As Date)
End Property

Public Property Get Reposicao() As Date
End Property

Public Property Let Reposicao(ByVal Data As Date)
End Property

Public Property Get Tipo() As Integer
End Property
Public Property Let Tipo(ByVal Tipo As Integer)
End Property

Public Property Get Dias() As Integer
End Property
Public Property Let Dias(ByVal Dias As Integer)
End Property

Public Property Get Adm() As Integer
End Property
Public Property Let Adm(ByVal Adm As Integer)
End Property

Public Property Get MaspDv() As Long
End Property
Public Property Let MaspDv(ByVal MaspDv As Long)
End Property

Public Property Get Quantidade() As Integer
End Property
Public Property Let Quantidade(ByVal Quantidade As Integer)
End Property

Public Property Get NaturezaQuantidade() As Long
End Property
Public Property Let NaturezaQuantidade(ByVal NaturezaQuantidade As Long)
End Property

Public Property Get Complementar() As Integer
End Property
Public Property Let Complementar(ByVal Complementar As Integer)
End Property

Public Property Get NaturezaComplementar() As Long
End Property
Public Property Let NaturezaComplementar(ByVal NaturezaComplementar As Long)
End Property

Public Property Get Carreira() As String
End Property
Public Property Let Carreira(ByVal Carreira_ As String)
End Property
