VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IRelatorio"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function Imprimir()
End Function

Public Function Limpar()
End Function

Public Function Inserir(Dados() As Variant)
End Function

Public Function ApagaLinhaTabela(ByVal Linha As Long)
End Function
Public Function AtualizaFormulario()
End Function
